config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :items, :only => [:new, :create, :edit, :update]
    delete 'clear', :on => :member
  end
  root 'projects#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :project
  validates :action,
    :presence => true,
    :uniqueness => { :scope => :project,
                     :message => 'should be unique within a project' }
  validates :project_id, :presence => true
  scope :complete, -> { where(:done => true) }
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :title, :presence => true
  has_many :items, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :get_project

  def new
    @item = @project.items.build
  end

  def create
    @item = @project.items.build(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to project_path(@project),
                      :notice => 'Item was successfully created.' }
        format.json { render :json => @item }
      else
        format.html { render :action => 'new' }
      end
    end
  end

  def edit
    @item = @project.items.find(params[:id])
  end

  def update
    @item = @project.items.find(params[:id])

    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to project_path(@project),
                      :notice => 'Item was successfully updated.' }
        format.json { render :json => @item }
      else
        format.html { render :action => 'edit' }
      end
    end
  end

private

  def get_project
    @project = Project.find(params[:project_id])
  end

  def item_params
    params.require(:item).permit(:action, :done)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, :except => [:index, :new, :create]

  def index
    @projects = Project.all
    respond_to do |format|
      format.html
      format.json { render :json => @projects }
    end
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_path(@project),
                      :notice => 'Project was successfully created.' }
        format.json { render :json => @project }
      else
        format.html { render :action => 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_path(@project),
                      :notice => 'Project was successfully updated.' }
        format.json { render :json => @project }
      else
        format.html { render :action => 'edit' }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_path,
                    :notice => 'Project was successfully destroyed.' }
      format.json { render :json => {'notice': 'Project was sucessfully destroyed'}}
    end
  end

  def clear
    @project.items.complete.destroy_all
    respond_to do |format|
      format.html { redirect_to project_path(@project),
                    :notice => 'Completed items were successfully cleared.' }
      format.json { render :json => {'notice': 'Completed items were successfully cleared.'} }
    end
  end

private
  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_index.html.erb
<ul>
  <% if @project.items.empty? %>
  <li>No items.</li>
  <% end %>
<% @project.items.each do |item| %>
  <li class="<%= "#{item.done? ? 'done' : 'not-done'}" %>">
    <%= link_to item.action, edit_project_item_path(@project, item) %>
    <% unless item.done? %>
      <%= button_to 'Done',
            { :controller => :items, :action => :update,
              :id => item.id, :project_id => @project.id,
              :item => { :done => true } },
            { :method => :patch } %>
    <% end %>
  </li>
<% end %>
</ul>

<%= link_to 'New Item', new_project_item_path(project) %>
<%= link_to 'Clear Completed Items', clear_project_path(project),
      :method => :delete, :id => "clearer" %>

app/views/items/edit.html.erb
<h2>Edit Item</h2>
<%= form_for([@project, @item], :url => { :action => :update }) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@item.errors.count, "error") %>
        prohibited this project from being saved:
      </h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :action %><br>
    <%= f.text_field :action, :size => "80" %>
  </div>
  <div class="field">
    <%= f.label :done, 'Done?' %>
    <%= f.check_box :done %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/new.html.erb
<h2>New Item</h2>
<%= form_for([@project, @item]) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@item.errors.count, "error") %>
        prohibited this project from being saved:
      </h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :action %><br>
    <%= f.text_field :action, :size => "80" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <!--[if lt IE 9]>
    <script src="http://html5.shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <title>Todo App</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <h1>Todo app</h1>
      <nav>
        <ul>
          <li><%= link_to 'Projects', projects_path %></li>
        </ul>
      </nav>
    </header>

    <div id="main">
      <p id="notice"><%= notice %></p>
      <%= yield %>
    </div>

    <footer>
      <p>2015</p>
    </footer>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.errors.count, "error") %>
        prohibited this project from being saved:
      </h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :size => "80" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

  <script type="text/javascript">
  var auth_token = $('input[name="authenticity_token"]').val();
  var utf8 = '✓';
  var $title = $('#project_title');

  function test_save()
  {
    $.ajax({ url: '/projects.json', type: 'post',
      data: {
        project: { title: $title.val()},
        utf8: utf8,
        autheticity_token: auth_token,
      }
    });
  }
  </script>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit Project</h2>

<%= render 'form' %>

app/views/projects/index.html.erb
<h2>Projects</h2>

<ul>
  <% if @projects.empty? %>
  <li>No projects.</li>
  <% end %>
<% @projects.each do |project| %>
<li>
  <%= link_to project.title,  project_path(project) %>
  <span>
    <%= link_to 'Destroy', project,
                method: :delete, data: { confirm: 'Are you sure?' } %>
  </span>
</li>
<% end %>
</ul>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h2><%= link_to @project.title, edit_project_path(@project) %> Items</h2>
<%= render :partial => 'items/index', :locals => { :project => @project } %>